VILLES = [
    "paris",
    "marseille",
    "lyon",
    "toulouse",
    "nice",
    "nantes",
    "montpellier",
    "strasbourg",
    "bordeaux",
    "lille",
    "rennes",
    "reims",
    "saint etienne",
    "toulon",
    "le havre",
    "grenoble",
    "dijon",
    "angers",
    "nimes",
    "villeurbanne",
    "le mans",
    "aix en provence",
    "brest",
    "clermont ferrand",
    "limoges",
    "tours",
    "amiens",
    "metz",
    "besancon",
    "perpignan",
    "orleans",
    "mulhouse",
    "rouen",
    "caen",
    "nancy",
    "argenteuil",
    "montreuil",
    "roubaix",
    "avignon",
    "tourcoing",
    "poitiers",
    "versailles",
    "pau",
    "la rochelle",
    "calais",
    "cannes",
    "antibes",
    "bourges",
    "cherbourg",
    "colmar",
    "annecy",
    "bayonne",
    "beziers",
    "ajaccio",
    "albi",
    "alencon",
    "angouleme",
    "arles",
    "arras",
    "auxerre",
    "aurillac",
    "blois",
    "brive la gaillarde",
    "carcassonne",
    "castres",
    "chambery",
    "chartres",
    "cholet",
    "compiegne",
    "dieppe",
    "douai",
    "draguignan",
    "dunkerque",
    "epinal",
    "evreux",
    "frejus",
    "gap",
    "hyeres",
    "la roche sur yon",
    "lens",
    "lorient",
    "macon",
    "montauban",
    "narbonne",
    "nevers",
    "niort",
    "quimper",
    "roanne",
    "rodez",
    "saint brieuc",
    "saint malo",
    "saint nazaire",
    "sete",
    "tarbes",
    "valence",
    "vannes",
    "vichy",
    "hebecourt",
    "etables",
    "etables sur mer",
    "gisors",
    "binic",
    "fontvieille",
    "arles",
    "saint remy de provence",
    "saintes maries de la mer"
]
